system:
  config:
    # CORS 跨域設定
    allowed-origins:
      - http://127.0.0.2:3000

    # 不受權限控管的網址
    permit-all-urls:
      - /security/check
      - /api/test/**
      - /api/qq/valid
    
    # 系統登入路徑
    login-path: /login
